Refactor scripts

diff --git a/script/cheat b/script/cheat
--- a/script/cheat
+++ b/script/cheat
@@ -1,1 +1,9 @@
-bash/cheat.sh
+#!/usr/bin/env bash
+
+if [ -z "$1" ]; then
+    echo "error: missing argument"
+    exit 1
+fi
+
+curl "cheat.sh/$1"
+
